staticPages:
  extraCss:
    - 'assets/css/plugins.scss'
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: true
    includeBreadcrumbs: false

showcase:
  layoutConfig:
    includeBreadcrumbs: true
