sections:
  'user-manual':
    title: 'User Manual'
    createPdf: false
  'learn':
    title: 'Tutorials'
    createPdf: false

wikiPages:
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: true
    includeBreadcrumbs: true
    pageContentsMenu:
      - type: 'separator'
        title: 'In This Page'
      - type: 'pageIds'
        structure: nested
        maxLevel: 2

'user-manual':
  menu:
    - type: 'separator'
      title: 'User Manual'
      order: 1000
    - type: 'wiki'
      section: 'user-manual'
      order: 1010

indexPages:
  template: 'wikiIndexPage'
  layoutConfig:
    includePageContentsMenu: false
