version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --no-daemon

test_script:
  - gradlew.bat check --no-daemon

branches:
  only:
    - master
    - dev

cache:
  - C:\Users\appveyor\.gradle

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
