name: Check

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: 'Test on ${{ matrix.os }} JDK ${{ matrix.jdk_version }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk_version: ['8', '9', '13', '16']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk_version }}
      - name: 'Build with Gradle'
        run: './gradlew assemble'
      - name: 'Run checks with Gradle'
        run: './gradlew check'
