name: Check Release

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Check ${{ matrix.os }} JDK ${{ matrix.jdk_version }} For Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk_version: ['8', '11', '15']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.jdk_version }}
    - name: Build with Gradle
      run: ./gradlew build -PorchidEnvironment=prod -Prelease
    - name: Build maven
      run: |
        cd buildSrc/orchidMavenPlugin
        ./mvnw package
