name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Publish package
        run: |
          ./gradlew assemble publishToMavenLocal publish -PorchidEnvironment=prod -Prelease
          ./gradlew publishPlugins -b buildSrc/orchidPlugin/build.gradle.kts -PorchidEnvironment=prod -Prelease
          |
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
      - name: extract version
        run:
      - name: Publish maven
        run:  |
          export GRADLE_PROJECT_RELEASE_NAME=$(./gradlew getReleaseName -Prelease --quiet)
          cd buildSrc/orchidMavenPlugin
          ./mvnw versions:set -DnewVersion=$GRADLE_PROJECT_RELEASE_NAME
          ./mvnw deploy
          |
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
